before_script:
  - "cd node_modules/sequelize-extra/node_modules/"
  - "rm -rf sequelize"
  - "git clone --branch=master git://github.com/sequelize/sequelize.git"
  - "cd sequelize"
  - "npm install --production"
  - "cd ../../../../"
  - "mysql -e 'create database sequelize_test;'"
  - "psql -c 'create database sequelize_test;' -U postgres"
  - "export SEQ_USER=travis"

script:
  - "make test"

language: node_js

node_js:
  - "0.10"

branches:
  only:
    - master
    - dev

cache:
  directories:
    - node_modules
