before_script:
  - "mysql -e 'create database sequelize_test;'"
  - "psql -c 'create database sequelize_test;' -U postgres"
  - "export SEQ_USER=travis"

script:
  - "make test"

language: node_js

node_js:
  - "0.10"

matrix:
  fast_finish: true
  include:
    - node_js: "0.10"
      env:
        - TEST_SUITE=test
        - COVERAGE=true
  allow_failures:
    - env:
        - TEST_SUITE=test
        - COVERAGE=true

branches:
  only:
    - master
    - dev

sudo: false
