before_script:
  - "mysql -e 'create database sequelize_test;'"
  - "psql -c 'create database sequelize_test;' -U postgres"
  - "export SEQ_USER=travis"

script:
  - "make test"

language: node_js

node_js:
  - "0.10"

branches:
  only:
    - master
    - dev

sudo: false
